version: '3'

volumes:
  error_handler_local_postgres_data: {}
  error_handler_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: error_handler_local_django
    container_name: error_handler_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: error_handler_production_postgres
    container_name: error_handler_local_postgres
    volumes:
      - error_handler_local_postgres_data:/var/lib/postgresql/data
      - error_handler_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: error_handler_local_redis

  celeryworker:
    <<: *django
    image: error_handler_local_celeryworker
    container_name: error_handler_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: error_handler_local_celerybeat
    container_name: error_handler_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: error_handler_local_flower
    container_name: error_handler_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
